/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.gltf --output components/Scene.jsx 
Author: moyicat (https://sketchfab.com/moyicat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-planet-of-the-little-prince-magicavoxel-8a7cf90ac42c4ef693342404826c06ae
Title: Voxel Planet of the Little Prince / MagicaVoxel
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[26.114, 5.488, 0]} rotation={[-Math.PI / 2, -0.43, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.palette}
          position={[-57.5, -62.5, 8]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
